// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9IHF5TuIq1FTpBtHzTBKclJV_E1RRl2o',
    appId: '1:744395738191:web:004513db241e3e5488ae3a',
    messagingSenderId: '744395738191',
    projectId: 'speech-therapy-evolution-dev',
    authDomain: 'speech-therapy-evolution-dev.firebaseapp.com',
    storageBucket: 'speech-therapy-evolution-dev.firebasestorage.app',
    measurementId: 'G-NQLWY4P60C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbIe5NlP5b2xG3Ex6Wq8Ki23wo2U0Tlh8',
    appId: '1:744395738191:android:29732a7210ed250f88ae3a',
    messagingSenderId: '744395738191',
    projectId: 'speech-therapy-evolution-dev',
    storageBucket: 'speech-therapy-evolution-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjzUTDCBgsQM37A6nBYGkJEgcm8AUS7GA',
    appId: '1:744395738191:ios:a1b7bc5eafb542a788ae3a',
    messagingSenderId: '744395738191',
    projectId: 'speech-therapy-evolution-dev',
    storageBucket: 'speech-therapy-evolution-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterTherapyEvolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjzUTDCBgsQM37A6nBYGkJEgcm8AUS7GA',
    appId: '1:744395738191:ios:7c21fde6aedb221188ae3a',
    messagingSenderId: '744395738191',
    projectId: 'speech-therapy-evolution-dev',
    storageBucket: 'speech-therapy-evolution-dev.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9IHF5TuIq1FTpBtHzTBKclJV_E1RRl2o',
    appId: '1:744395738191:web:194cb7f6f0d8520288ae3a',
    messagingSenderId: '744395738191',
    projectId: 'speech-therapy-evolution-dev',
    authDomain: 'speech-therapy-evolution-dev.firebaseapp.com',
    storageBucket: 'speech-therapy-evolution-dev.firebasestorage.app',
    measurementId: 'G-CLFHB29Z0T',
  );
}
